POST http://symfony.localhost/apply
Content-Type: application/json

{
   "items": [
       {
           "id": 1,
           "price": 399
       },
       {
           "id": 2,
           "price": 600
       },
     {
       "id": 3,
         "price": 600
     },
       {
           "id": 4,
           "price": 1000
       }
   ],
   "code": "UNDOKZI"
}
